"""
Scenario Engine domain.

Tables
------
scenario_questions  — LLM-generated question for a job posting. One active
                      question per posting at any time (can be regenerated).
scenario_responses  — a candidate's timed answer to the scenario question,
                      plus anti-gaming signals and the AI evaluation summary.
"""

import uuid
from typing import TYPE_CHECKING, Optional

from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, UUIDMixin

if TYPE_CHECKING:
    from .application import Application
    from .job import JobPosting


# ---------------------------------------------------------------------------
# scenario_questions
# ---------------------------------------------------------------------------


class ScenarioQuestion(UUIDMixin, Base):
    """
    A scenario question generated by the LLM for a specific job posting.

    Design notes
    ------------
    - One JobPosting can have multiple questions over time (regenerated when the
      employer requests a refresh), but only the latest is served to candidates.
      Use generated_at DESC to find the active one.
    - time_limit_seconds is configurable per-posting (default 300 = 5 minutes).
      The frontend enforces the timer; the backend stores submission timestamp
      and checks elapsed time server-side to flag violations.
    - question_text is stored as plain text (no HTML) to prevent injection into
      the isolated test environment.
    """

    __tablename__ = "scenario_questions"

    job_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("job_postings.id", ondelete="CASCADE"),
        nullable=False,
    )
    question_text: Mapped[str] = mapped_column(Text, nullable=False)
    time_limit_seconds: Mapped[int] = mapped_column(
        Integer, default=300, server_default="300"
    )
    generated_at: Mapped[object] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationships
    job_posting: Mapped["JobPosting"] = relationship(back_populates="scenario_questions")
    responses: Mapped[list] = relationship(
        "ScenarioResponse", back_populates="question", lazy="select"
    )

    __table_args__ = (
        # Fetch active question for a job: ORDER BY generated_at DESC LIMIT 1
        Index("ix_scenario_questions_job_id_generated_at", "job_id", "generated_at"),
    )

    def __repr__(self) -> str:
        return f"<ScenarioQuestion job={self.job_id} generated_at={self.generated_at}>"


# ---------------------------------------------------------------------------
# scenario_responses
# ---------------------------------------------------------------------------


class ScenarioResponse(UUIDMixin, Base):
    """
    A candidate's answer to a scenario question.

    Design notes
    ------------
    - One application can have at most one scenario response (enforced via
      unique constraint on application_id).
    - score (0.0–1.0) is the LLM's numerical evaluation of the answer quality.
    - ai_summary is a ~3-sentence plain-text explanation shown to the employer
      describing how the response aligns with the scenario and role.
    - paste_detected / tab_switches are anti-gaming signals. They are NEVER
      used to auto-reject — they are surfaced to the employer as context flags
      so they can make an informed decision.
    - time_taken_seconds is computed server-side: submitted_at - question served_at.
      If it's less than 10 seconds, that's flagged too (copy-paste from elsewhere).
    """

    __tablename__ = "scenario_responses"

    application_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("applications.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,  # one response per application
    )
    question_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("scenario_questions.id", ondelete="RESTRICT"),
        nullable=False,
    )

    response_text: Mapped[str] = mapped_column(Text, nullable=False)

    # LLM evaluation
    score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ai_summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Anti-gaming signals (employer-visible, never auto-reject)
    paste_detected: Mapped[bool] = mapped_column(
        Boolean, default=False, server_default="false"
    )
    tab_switches: Mapped[int] = mapped_column(Integer, default=0, server_default="0")
    time_taken_seconds: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    submitted_at: Mapped[object] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationships
    application: Mapped["Application"] = relationship(back_populates="scenario_response")
    question: Mapped["ScenarioQuestion"] = relationship(back_populates="responses")

    __table_args__ = (
        Index("ix_scenario_responses_application_id", "application_id"),
        Index("ix_scenario_responses_question_id", "question_id"),
    )

    def __repr__(self) -> str:
        return (
            f"<ScenarioResponse application={self.application_id} score={self.score}>"
        )