"""Added a Job type

Revision ID: 228691da6275
Revises: dcf24a37a00d
Create Date: 2026-08-31 16:36:32.709748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '228691da6275'
down_revision: Union[str, Sequence[str], None] = 'dcf24a37a00d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # PostgreSQL enum types must exist before a column can reference them.
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'job_type_enum') THEN
                CREATE TYPE job_type_enum AS ENUM ('full_time', 'part_time', 'contract', 'internship');
            END IF;
        END
        $$;
        """
    )
    op.add_column(
        'job_postings',
        sa.Column(
            'job_type',
            sa.Enum('full_time', 'part_time', 'contract', 'internship', name='job_type_enum'),
            nullable=True,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('job_postings', 'job_type')
    op.execute("DROP TYPE IF EXISTS job_type_enum")
    
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
