"""add is_deleted to resume_versions

Revision ID: 2c0722d43bcf
Revises: 7f0719e79df9
Create Date: 2026-07-09 12:22:04.428562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c0722d43bcf'
down_revision: Union[str, Sequence[str], None] = '7f0719e79df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_versions', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.create_index('ix_resume_versions_candidate_id_is_deleted', 'resume_versions', ['candidate_id', 'is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resume_versions_candidate_id_is_deleted', table_name='resume_versions')
    op.drop_column('resume_versions', 'is_deleted')
    # ### end Alembic commands ###
