"""add scenario_score_threshold to job_postings

Revision ID: 7580b8fade0c
Revises: b24d46d50333
Create Date: 2026-07-15 17:47:57.443689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7580b8fade0c'
down_revision: Union[str, Sequence[str], None] = 'b24d46d50333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('scenario_score_threshold', sa.Float(), server_default='0.5', nullable=False))
    op.alter_column('scenario_questions', 'application_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenario_questions', 'application_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('job_postings', 'scenario_score_threshold')
    # ### end Alembic commands ###
