"""add label to resume_versions

Revision ID: 7f0719e79df9
Revises: b0a2d3129bf0
Create Date: 2026-07-01 16:41:08.132841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0719e79df9'
down_revision: Union[str, Sequence[str], None] = 'b0a2d3129bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_versions', sa.Column('label', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_versions', 'label')
    # ### end Alembic commands ###
