"""Added file Size in resume

Revision ID: 839a023c1095
Revises: 228691da6275
Create Date: 2026-09-07 11:14:59.145325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839a023c1095'
down_revision: Union[str, Sequence[str], None] = '228691da6275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_versions', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    op.add_column('resume_versions', sa.Column('content_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_versions', 'content_type')
    op.drop_column('resume_versions', 'file_size_bytes')
    # ### end Alembic commands ###
