"""add categories cache to candidate_profiles

Revision ID: b0a2d3129bf0
Revises: d8edeac5752a
Create Date: 2026-07-01 15:26:50.465198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0a2d3129bf0'
down_revision: Union[str, Sequence[str], None] = 'd8edeac5752a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('categories', postgresql.ARRAY(sa.String(length=50)), nullable=True))
    op.create_index('ix_candidate_profiles_categories', 'candidate_profiles', ['categories'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidate_profiles_categories', table_name='candidate_profiles', postgresql_using='gin')
    op.drop_column('candidate_profiles', 'categories')
    # ### end Alembic commands ###
