"""scenario_questions: scope to application instead of job

Revision ID: b24d46d50333
Revises: 2c0722d43bcf
Create Date: 2026-07-15 15:17:46.073142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b24d46d50333'
down_revision: Union[str, Sequence[str], None] = '2c0722d43bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_questions', sa.Column('application_id', sa.UUID(), nullable=True))
    op.add_column('scenario_questions', sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_scenario_questions_job_id_generated_at'), table_name='scenario_questions')
    op.create_index('ix_scenario_questions_application_id', 'scenario_questions', ['application_id'], unique=False)
    op.create_unique_constraint('uq_scenario_questions_application_id', 'scenario_questions', ['application_id'])
    op.drop_constraint(op.f('scenario_questions_job_id_fkey'), 'scenario_questions', type_='foreignkey')
    op.create_foreign_key('fk_scenario_questions_application_id_applications', 'scenario_questions', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_column('scenario_questions', 'job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_questions', sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_scenario_questions_application_id_applications', 'scenario_questions', type_='foreignkey')
    op.create_foreign_key(op.f('scenario_questions_job_id_fkey'), 'scenario_questions', 'job_postings', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_scenario_questions_application_id', 'scenario_questions', type_='unique')
    op.drop_index('ix_scenario_questions_application_id', table_name='scenario_questions')
    op.create_index(op.f('ix_scenario_questions_job_id_generated_at'), 'scenario_questions', ['job_id', 'generated_at'], unique=False)
    op.drop_column('scenario_questions', 'started_at')
    op.drop_column('scenario_questions', 'application_id')
    # ### end Alembic commands ###
