"""fix org_invites role column

Revision ID: b4d082eecec7
Revises: be4270a20c97
Create Date: 2026-06-18 12:26:13.760608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d082eecec7'
down_revision: Union[str, Sequence[str], None] = 'be4270a20c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_invites', sa.Column('role', sa.Enum('owner', 'recruiter', 'viewer', name='org_role_enum'), server_default='recruiter', nullable=False))
    op.drop_constraint(op.f('uq_org_invite_pending'), 'org_invites', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_org_invite_pending'), 'org_invites', ['org_id', 'invited_email', 'direction', 'status'], postgresql_nulls_not_distinct=False)
    op.drop_column('org_invites', 'role')
    # ### end Alembic commands ###
