"""Created organisation invites

Revision ID: be4270a20c97
Revises: 0001
Create Date: 2026-06-17 16:33:23.235767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be4270a20c97'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_invites',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('invited_email', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.Enum('invite', 'request', name='invite_direction_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'expired', 'cancelled', name='invite_status_enum'), server_default='pending', nullable=False),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'invited_email', 'direction', 'status', name='uq_org_invite_pending'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_org_invites_invited_email', 'org_invites', ['invited_email'], unique=False)
    op.create_index('ix_org_invites_org_id', 'org_invites', ['org_id'], unique=False)
    op.create_index('ix_org_invites_token', 'org_invites', ['token'], unique=False)
    op.add_column('audit_logs', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('audit_logs', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('audit_logs', 'meta_data')
    op.drop_index('ix_org_invites_token', table_name='org_invites')
    op.drop_index('ix_org_invites_org_id', table_name='org_invites')
    op.drop_index('ix_org_invites_invited_email', table_name='org_invites')
    op.drop_table('org_invites')
    # ### end Alembic commands ###
