"""add parsed_data and categories to resumes and job_postings

Revision ID: d8edeac5752a
Revises: 17861bce31c1
Create Date: 2026-07-01 14:25:13.873151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8edeac5752a'
down_revision: Union[str, Sequence[str], None] = '17861bce31c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('job_postings', sa.Column('categories', postgresql.ARRAY(sa.String(length=50)), nullable=True))
    op.create_index('ix_job_postings_categories', 'job_postings', ['categories'], unique=False, postgresql_using='gin')
    op.add_column('resume_versions', sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('resume_versions', sa.Column('categories', postgresql.ARRAY(sa.String(length=50)), nullable=True))
    op.create_index('ix_resume_versions_categories', 'resume_versions', ['categories'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resume_versions_categories', table_name='resume_versions', postgresql_using='gin')
    op.drop_column('resume_versions', 'categories')
    op.drop_column('resume_versions', 'parsed_data')
    op.drop_index('ix_job_postings_categories', table_name='job_postings', postgresql_using='gin')
    op.drop_column('job_postings', 'categories')
    op.drop_column('job_postings', 'parsed_data')
    # ### end Alembic commands ###
