"""Org edit function

Revision ID: dcf24a37a00d
Revises: add_question_pool
Create Date: 2026-08-30 23:22:10.897845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcf24a37a00d'
down_revision: Union[str, Sequence[str], None] = 'add_question_pool'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_messages_org_id_sent_at'), table_name='org_messages')
    op.drop_table('org_messages')
    op.add_column('organizations', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('company_size', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'logo_url')
    op.drop_column('organizations', 'company_size')
    op.drop_column('organizations', 'industry')
    op.drop_column('organizations', 'website')
    op.drop_column('organizations', 'description')
    op.create_table('org_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('org_messages_org_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('org_messages_sender_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('org_messages_pkey'))
    )
    op.create_index(op.f('ix_org_messages_org_id_sent_at'), 'org_messages', ['org_id', 'sent_at'], unique=False)
    # ### end Alembic commands ###
