"""add override_apps_reset_at to candidate_profiles

Revision ID: f8271d140caa
Revises: 7580b8fade0c
Create Date: 2026-07-16 15:49:45.289193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8271d140caa'
down_revision: Union[str, Sequence[str], None] = '7580b8fade0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('override_apps_reset_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'override_apps_reset_at')
    # ### end Alembic commands ###
